---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/products/{id}":
    get:
      summary: Retrieves a product
      tags:
      - products
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: product found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                required:
                - id
                - title
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                required:
                - id
                - title
        '404':
          description: product not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: https://kodingroo.jp.ngrok.io
